// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFIyGYnmBLD7amaPFQnxIFP8mdOSeim90',
    appId: '1:972323539727:web:177950fad52b33f1f88c7a',
    messagingSenderId: '972323539727',
    projectId: 'realestate-e184e',
    authDomain: 'realestate-e184e.firebaseapp.com',
    storageBucket: 'realestate-e184e.appspot.com',
    measurementId: 'G-NB6CJRMJMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMJPV7lHFiMU1NwThMBd3Xd1AQnLXsmPg',
    appId: '1:972323539727:android:28c92ffd816fdd2ff88c7a',
    messagingSenderId: '972323539727',
    projectId: 'realestate-e184e',
    storageBucket: 'realestate-e184e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPGUoeSJDfFYSlnJrFi_CXSKzeZKccHic',
    appId: '1:972323539727:ios:36e892e2bef2e3fff88c7a',
    messagingSenderId: '972323539727',
    projectId: 'realestate-e184e',
    storageBucket: 'realestate-e184e.appspot.com',
    iosClientId: '972323539727-jijmgo6ntoqse27tddehr8hru6gaj951.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPGUoeSJDfFYSlnJrFi_CXSKzeZKccHic',
    appId: '1:972323539727:ios:927eb26fb2d996d9f88c7a',
    messagingSenderId: '972323539727',
    projectId: 'realestate-e184e',
    storageBucket: 'realestate-e184e.appspot.com',
    iosClientId: '972323539727-hdat8t9h37oua6htgbd5gs4ua8ee98pq.apps.googleusercontent.com',
    iosBundleId: 'com.example.realEstateRunnerTests',
  );
}
