// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFIyGYnmBLD7amaPFQnxIFP8mdOSeim90',
    appId: '1:972323539727:android:28c92ffd816fdd2ff88c7a',//
    messagingSenderId: '988747769378',//
    projectId: 'realestate-e184e',//
    authDomain: 'gmsmobile-1df6b.firebaseapp.com',
    storageBucket: 'gmsmobile-1df6b.appspot.com',
    measurementId: 'G-SVNS6BH0M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgyQFBtjDHY7KaRwuCLI4twBK9KR_OMfc',
    appId: '1:972323539727:android:28c92ffd816fdd2ff88c7a',
    messagingSenderId: '988747769378',
    projectId: 'realestate-e184e',
    storageBucket: 'gmsmobile-1df6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAX3DmJcxKDqjRqFb9iLBufPuVwftUg0q8',
    appId: '1:972323539727:android:28c92ffd816fdd2ff88c7a',
    messagingSenderId: '988747769378',
    projectId: 'realestate-e184e',
    storageBucket: 'gmsmobile-1df6b.appspot.com',
    iosClientId: '988747769378-v924ivrnjeo36oq5ea669qk1g3s1dfpu.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmsfluttermobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAX3DmJcxKDqjRqFb9iLBufPuVwftUg0q8',
    appId: '1:972323539727:android:28c92ffd816fdd2ff88c7a',
    messagingSenderId: '988747769378',
    projectId: 'realestate-e184e',
    storageBucket: 'gmsmobile-1df6b.appspot.com',
    iosClientId: '988747769378-a1atqus3fu9ar72g372c4g8eejurvid8.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmsfluttermobile.RunnerTests',
  );
}
